services:
  db:
    image: postgres:16.4-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${PROJECT_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
